import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  const browserErrors: string[] = []
  page.on('console', message => {
    if (message.type() === 'error') browserErrors.push(`console: ${message.text()}`)
  })
  page.on('pageerror', error => browserErrors.push(`pageerror: ${error.message}`))
  ;(page as typeof page & { browserErrors?: string[] }).browserErrors = browserErrors
})

test.afterEach(async ({ page }) => {
  const browserErrors = (page as typeof page & { browserErrors?: string[] }).browserErrors ?? []
  expect(browserErrors, `Browser errors:\n${browserErrors.join('\n')}`).toEqual([])
})

async function enterWorkspace(page: import('@playwright/test').Page) {
  await page.goto('/')
  await page.getByRole('button', { name: /enter workspace/i }).click()
  await expect(page.getByRole('heading', { name: 'Voice procurement' })).toBeVisible()
}

test('slang-heavy voice request can be structured, reviewed, and created', async ({ page }) => {
  await enterWorkspace(page)
  await page.getByRole('button', { name: /Talk to Sarah|Start talking/ }).first().click()
  const dialog = page.getByRole('dialog', { name: 'Sarah' })
  await dialog.getByLabel('Your request').fill('Need half a dozen boxes of fresh halal chicken breast fillets delivered to 24 Flinders Lane, Melbourne VIC 3000 tomoz before eight in the morning, under three hundred and fifty bucks, a fortnight from invoice and nothing upfront mate. Compare a few suppliers and let me choose.')
  await dialog.getByRole('button', { name: /review structured request/i }).click()

  await expect(page.getByRole('dialog', { name: 'Review your request' })).toBeVisible()
  await expect(page.getByLabel('Structured request review')).toContainText('Structured locally')
  await expect(page.getByLabel('Item')).toHaveValue(/chicken breast/i)
  await expect(page.getByLabel('Quantity')).toHaveValue('6')
  await expect(page.getByLabel('Unit')).toHaveValue('boxes')
  await expect(page.getByLabel('Maximum budget (AUD)')).toHaveValue('350')
  await expect(page.getByLabel('Delivery address')).toHaveValue(/Flinders Lane/i)
  const reviewDialog = page.getByRole('dialog', { name: 'Review your request' })
  await expect(reviewDialog.getByLabel('Sourcing approach')).toHaveValue('compare')
  await expect(reviewDialog.getByLabel('When a quote meets every requirement')).toHaveValue('confirm')
  await page.getByRole('button', { name: /confirm & create request/i }).click()

  await expect(page.getByRole('heading', { name: 'Requests', exact: true }).first()).toBeVisible()
  await expect(page.getByText('Chicken breast', { exact: false }).first()).toBeVisible()
  await expect(page.getByRole('status')).toContainText('Request created')
})

test('Michelle can review and store the FreshFoods pre-authorisation limits', async ({ page }) => {
  await enterWorkspace(page)
  await page.getByRole('button', { name: /Talk to Sarah|Start talking/ }).first().click()
  const dialog = page.getByRole('dialog', { name: 'Sarah' })
  await dialog.getByLabel('Your request').fill('Sarah, call FreshFoods and negotiate an order for 40 kilograms of chicken thighs, delivered by Friday. My maximum budget is $260, with a deposit no higher than 10 per cent. If every condition is met, you can send one purchase order.')
  await dialog.getByRole('button', { name: /review structured request/i }).click()

  const review = page.getByRole('dialog', { name: 'Review your request' })
  await expect(review.getByLabel('Item')).toHaveValue('chicken thighs')
  await expect(review.getByLabel('Quantity')).toHaveValue('40')
  await expect(review.getByLabel('Unit')).toHaveValue('kg')
  await expect(review.getByLabel('Maximum budget (AUD)')).toHaveValue('260')
  await review.getByLabel('Required by').fill('2026-09-18T17:00')
  await review.getByLabel('Delivery address').fill('Michelle’s Restaurant, Melbourne')
  await review.getByLabel('Halal requirement').selectOption('no')
  await review.getByLabel('Cut or format').fill('thighs')
  await review.getByLabel('Freshness').selectOption('fresh')
  await review.locator('details.request-preferences > summary').click()
  await review.locator('details.payment-preferences > summary').click()
  await review.getByLabel('Minimum days from invoice').selectOption('0')
  await expect(review.getByLabel('Maximum deposit')).toHaveValue('10')
  await expect(review.getByLabel('Sourcing approach')).toHaveValue('first_qualifying')
  await expect(review.getByLabel('When a quote meets every requirement')).toHaveValue('preauthorized')
  await expect(review).toContainText('pre-authorises one purchase order up to $260')
  await expect(review).toContainText('maximum 10% deposit')
  await review.getByRole('button', { name: /confirm & create request/i }).click()

  await expect(page.getByRole('status')).toContainText('Request created')
  await page.getByRole('button', { name: /Open REQ-.*, chicken thighs/i }).click()
  const drawer = page.getByRole('dialog', { name: 'chicken thighs' })
  await expect(drawer).toContainText('$260')
  await expect(drawer).toContainText('0+ days')
  await expect(drawer).toContainText('10%')
  await expect(drawer).toContainText('Pre-authorised')
})

test('manual request wizard completes all controls', async ({ page }) => {
  await enterWorkspace(page)
  await page.getByRole('button', { name: /^Requests/ }).click()
  await page.getByRole('button', { name: 'Add Request' }).click()
  const wizard = page.getByRole('dialog', { name: 'Add request' })
  await wizard.getByLabel('Item or product').fill('Compostable cups')
  await wizard.getByLabel('Category').fill('Hospitality supplies')
  await wizard.getByLabel('Quantity').fill('500')
  await wizard.getByRole('button', { name: 'Continue' }).click()
  await wizard.getByLabel('Maximum budget (AUD)').fill('240')
  await wizard.getByRole('button', { name: 'Continue' }).click()
  await wizard.getByLabel('Minimum payment terms').selectOption('14')
  await wizard.getByLabel('Sourcing approach').selectOption('compare')
  await wizard.getByLabel('Purchase approval').selectOption('confirm')
  await wizard.getByRole('button', { name: 'Add request' }).click()

  await expect(wizard).not.toBeVisible()
  await expect(page.getByRole('button', { name: /Compostable cups/i })).toBeVisible()
})

test('supplier import and call transcript workflows are reachable', async ({ page }) => {
  await enterWorkspace(page)
  await page.getByRole('button', { name: /^Suppliers$/ }).click()
  await page.getByRole('button', { name: 'Import supplier' }).click()
  const supplierDialog = page.getByRole('dialog', { name: 'Import supplier' })
  await supplierDialog.getByLabel('Business name').fill('E2E Wholesale')
  await supplierDialog.getByLabel('ABN').fill('51 824 753 556')
  await supplierDialog.getByLabel('Contact phone').fill('03 9000 0000')
  await supplierDialog.getByLabel('Supplier email').fill('orders@example.com')
  await supplierDialog.getByRole('button', { name: /check & queue for verification/i }).click()
  await expect(page.getByRole('heading', { name: 'E2E Wholesale' })).toBeVisible()
  await expect(page.getByText('Registry evidence pending')).toBeVisible()

  await page.getByRole('button', { name: 'Call activity', exact: true }).click()
  await page.getByRole('button', { name: /Victorian Foods/ }).click()
  const transcript = page.getByRole('dialog', { name: 'Call transcript' })
  await expect(transcript).toContainText('DEMO CALL TRANSCRIPT')
  await expect(transcript.getByText('SARAH · SOURCEPILOT AI').first()).toBeVisible()
  await expect(transcript.getByText('VICTORIAN FOODS').first()).toBeVisible()
  await expect(transcript.locator('.speech')).toHaveCount(5)
  await page.getByRole('button', { name: 'Back to workspace' }).click()
  await expect(page.getByRole('dialog', { name: 'Call transcript' })).not.toBeVisible()
})

test('both supplier sourcing strategies enforce the right approval behavior', async ({ page }) => {
  await enterWorkspace(page)
  await page.getByRole('button', { name: /^Requests/ }).click()
  await page.getByRole('button', { name: 'Add Request' }).click()
  const wizard = page.getByRole('dialog', { name: 'Add request' })
  await wizard.getByLabel('Item or product').fill('Cleaning cloths')
  await wizard.getByLabel('Category').fill('Cleaning')
  await wizard.getByLabel('Quantity').fill('100')
  await wizard.getByRole('button', { name: 'Continue' }).click()
  await wizard.getByLabel('Maximum budget (AUD)').fill('200')
  await wizard.getByRole('button', { name: 'Continue' }).click()
  const sourcing = wizard.getByLabel('Sourcing approach')
  const approval = wizard.getByLabel('Purchase approval')
  await sourcing.selectOption('compare')
  await expect(approval).toHaveValue('confirm')
  await expect(approval.locator('option[value="preauthorized"]')).toHaveAttribute('disabled', '')
  await sourcing.selectOption('first_qualifying')
  await approval.selectOption('preauthorized')
  await expect(approval).toHaveValue('preauthorized')
})
