import { useState } from 'react'
import { Check, Search, ShieldCheck, X } from 'lucide-react'
import { demoCandidates, discoveryFactors, discoveryProfiles, rankCandidates, type DiscoveryFactor, type DiscoveryProfileId } from '../features/discovery/engine'

const labels: Record<DiscoveryFactor, string> = {productMatch:'Product match',deliveryFit:'Delivery fit',landedCost:'Landed cost',reliability:'Reliability',locality:'Local proximity',paymentTerms:'Payment terms',certifications:'Certifications'}

export function DiscoveryPolicy() {
  const [profileId,setProfileId] = useState<DiscoveryProfileId>('hospitality')
  const profile = discoveryProfiles.find(item => item.id === profileId) ?? discoveryProfiles[0]
  const ranked = rankCandidates(demoCandidates, profile)
  return <section className="policy-panel"><div className="section-header"><div><h2>Supplier discovery policy</h2><p>AI broadens the search. Evidence and fixed rules decide who reaches the call queue.</p></div><span className="demo-badge">Explainable ranking</span></div><div className="policy-layout"><div className="policy-settings"><label>Buying profile<select value={profileId} onChange={event => setProfileId(event.target.value as DiscoveryProfileId)}>{discoveryProfiles.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p>{profile.description}</p><div className="weight-list">{discoveryFactors.map(factor => <div key={factor}><span>{labels[factor]}</span><span className="weight-track"><i style={{width:`${profile.weights[factor] * 3}%`}}/></span><strong>{profile.weights[factor]}%</strong></div>)}</div></div><div className="discovery-results"><div className="pipeline"><span><Search size={15}/> Semantic product recall</span><span><ShieldCheck size={15}/> Hard eligibility rules</span><span><Check size={15}/> Weighted business fit</span></div>{ranked.map((result,index) => <article className={`candidate-row ${result.eligible ? '' : 'blocked'}`} key={result.candidate.id}><span className="candidate-rank">{result.eligible ? index + 1 : <X size={15}/>}</span><div><strong>{result.candidate.name}</strong><p>{result.eligible ? `Eligible for outreach · ${result.reviewReasons.length ? result.reviewReasons.join(' · ') : 'Evidence complete'}` : result.blockers.join(' · ')}</p></div><b>{result.score}<small>/100</small></b></article>)}</div></div><p className="voice-message">Embeddings can retrieve suppliers whose catalogues use different product wording. A structured extraction model records facts and evidence. Neither can override ABN, authorisation, certification, opt-out, or minimum product-match rules.</p></section>
}
