import { useState } from 'react'
import { calculateQuote, formatCents, type QuoteInput } from '../features/negotiation/calculator'
import { assessConversation } from '../features/negotiation/signals'
export function NegotiationTools() {
  const [input,setInput] = useState<QuoteInput>({quantity:'30',unitPrice:'10.50',discount:'0',delivery:'0',fees:'0',taxRate:'0',deposit:'0',budget:'350'})
  const [text,setText] = useState('I’m busy, please make it quick. That is our final price.')
  const [counters,setCounters] = useState(0)
  const signal = assessConversation(text,counters)
  let result: ReturnType<typeof calculateQuote> | undefined, error=''
  try {result=calculateQuote(input)} catch(err) {error=err instanceof Error ? err.message : 'Check your numbers.'}
  return <section className="negotiation-tools"><div className="section-header"><div><h2>Negotiation desk</h2><p>Check the numbers and choose the next response.</p></div><span className="demo-badge">Local tools · No supplier contacted</span></div><div className="tool-grid"><section className="tool-card"><span className="eyebrow">FAST QUOTE MATH</span><h3>Know the full cost.</h3><div className="math-inputs">{([['quantity','Quantity'],['unitPrice','Unit price (AUD)'],['discount','Discount (%)'],['delivery','Delivery (AUD)'],['fees','Other fees (AUD)'],['taxRate','Additional tax (%)'],['deposit','Deposit (%)'],['budget','Total budget (AUD)']] as const).map(([key,label]) => <label key={key}>{label}<input inputMode="decimal" value={input[key]} onChange={e => setInput({...input,[key]:e.target.value})}/></label>)}</div><p className="voice-message">Use 0% additional tax when prices already include tax. Discounts apply to goods; additional tax applies to discounted goods, delivery and fees. Confirm this basis with the supplier.</p>{error ? <p className="form-error" role="status">{error}</p> : result && <div className="math-results" aria-live="polite"><div><span>Total payable</span><strong>{formatCents(result.total)}</strong></div><div><span>Discount saved</span><strong>{formatCents(result.discount)}</strong></div><div><span>Additional tax</span><strong>{formatCents(result.tax)}</strong></div><div><span>Deposit now</span><strong>{formatCents(result.deposit)}</strong></div><div><span>Remaining balance</span><strong>{formatCents(result.balance)}</strong></div><div className={result.withinBudget ? '' : 'form-error'}><span>{result.withinBudget ? 'Budget remaining' : 'Over budget'}</span><strong>{formatCents(result.headroom < 0n ? -result.headroom : result.headroom)}</strong></div></div>}</section><section className="tool-card"><span className="eyebrow">CONVERSATION CUES</span><h3>Adapt without pushing.</h3><label>Latest supplier message<textarea rows={4} value={text} onChange={e => setText(e.target.value)}/></label><label>Counteroffers already made<select value={counters} onChange={e => setCounters(Number(e.target.value))}><option value={0}>0</option><option value={1}>1</option><option value={2}>2 — stop bargaining</option></select></label><div className="signal-result" aria-live="polite"><strong>{signal.tone}</strong><p>{signal.pace}</p><p>Evidence: {signal.evidence.length ? signal.evidence.map(s => `“${s}”`).join(', ') : 'No explicit phrase found.'}</p><blockquote>{signal.response}</blockquote></div><p className="voice-message">Tentative, rule-based text cues—not an emotion or patience score. Audio, interruptions and response latency are not analysed yet. Suggestions are not sent to Sarah or the supplier.</p></section></div></section>
}
