import { useState } from 'react'
import { Check, Clock3, Plus, ShieldCheck, X } from 'lucide-react'
import { prepareSupplier, type ImportedSupplier } from '../features/suppliers/verification'
export function SupplierImport({suppliers,onImport}:{suppliers:ImportedSupplier[];onImport:(supplier:ImportedSupplier)=>void | Promise<void>}) {
  const [open,setOpen] = useState(false)
  const [saving,setSaving] = useState(false)
  const [error,setError] = useState('')
  return <section className="supplier-import"><div className="section-header"><div><h2>Supplier import queue</h2><p>Validate → check registry → match details → authorise.</p></div><button className="primary" onClick={() => setOpen(true)}><Plus size={17}/> Import supplier</button></div>{suppliers.length === 0 && <div className="import-empty"><ShieldCheck size={22}/><p>Imported suppliers stay outside your calling list until their business details are verified.</p></div>}{suppliers.map(s => <article className="import-record" key={s.id}><h3>{s.name}</h3><p>ABN {s.abn} · {s.phone}</p><div className="checks"><span><Check size={14}/> ABN checksum passed</span><span className="failed"><Clock3 size={14}/> Registry verification pending</span></div><ol><li>Confirm active ABN and legal/business name.</li><li>Review GST status and registered location.</li><li>Match contact details and relevant product certifications.</li><li>Owner authorises supplier for outreach.</li></ol><a className="text-button" href={`https://abr.business.gov.au/ABN/View?abn=${s.abn}`} target="_blank" rel="noreferrer">Open official ABN Lookup ↗</a><p className="voice-message">Live lookup is not connected. This record remains blocked from outreach; opening the registry does not mark it verified.</p></article>)}{open && <dialog className="voice-dialog" aria-labelledby="import-title" ref={node => {if(node && !node.open)node.showModal()}} onCancel={() => setOpen(false)}><form onSubmit={async e => {e.preventDefault();if(saving)return;setSaving(true);const data=new FormData(e.currentTarget);try {await onImport(prepareSupplier(String(data.get('name')),String(data.get('abn')),String(data.get('phone')),suppliers));setOpen(false);setError('')} catch(err) {setError(err instanceof Error ? err.message : 'Unable to import supplier.')}finally{setSaving(false)}}}><div className="modal-head"><h2 id="import-title">Import supplier</h2><button type="button" className="icon-button" aria-label="Close import" onClick={() => setOpen(false)}><X size={20}/></button></div><p className="muted">Add the supplier’s details for review. Importing never grants permission to call or buy.</p><label>Business name<input name="name" required maxLength={160}/></label><label>ABN<input name="abn" inputMode="numeric" placeholder="11 digits" required maxLength={20}/></label><label>Contact phone<input name="phone" type="tel" required maxLength={22}/></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary full" type="submit" disabled={saving}>{saving ? 'Saving…' : 'Check & queue for review'}</button><p className="voice-message">Checks run locally. Records save to Supabase when connected; demo imports last for this session.</p></form></dialog>}</section>
}
