import { useState } from 'react'
import { Mic, Activity, ArrowDownLeft, ArrowLeft, ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Clock3, FileText, LayoutDashboard, Mail, MapPin, MessageSquare, MoreHorizontal, Package, Phone, Plus, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react'
import { SupplierRanking } from './components/SupplierRanking'
import { paymentLabel } from './features/recoveries/ranking'
import { NewRecovery } from './components/NewRecovery'
import { initialRecoveries, offers, money, validateOffer, type Recovery, type Offer } from './features/recoveries/data'
type Page = 'Overview' | 'Recoveries' | 'Suppliers' | 'Call activity'
export default function App() {
  const [page, setPage] = useState<Page>('Overview')
  const [recoveries, setRecoveries] = useState(initialRecoveries)
  const [selected, setSelected] = useState('REC-024')
  const [tab, setTab] = useState('Overview')
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState(false)
  const [transcript, setTranscript] = useState<Offer | null>(null)
  const [notice, setNotice] = useState('')
  const request = recoveries.find(r => r.id === selected)!
  const seeded = request.id === 'REC-024'
  const approved = request.status === 'Approved'
  const filtered = recoveries.filter(r => `${r.item} ${r.id}`.toLowerCase().includes(query.toLowerCase()))
  const nav = (next: Page) => { setPage(next); setQuery('') }
  const notify = (message: string) => setNotice(message)
  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="#" onClick={() => nav('Overview')}><span className="brand-mark">b<span>↗</span></span>backfill<span className="brand-period">.</span></a>
      <div className="workspace"><span className="workspace-logo">F</span><div><strong>Flinders Kitchen</strong><small>Business workspace</small></div><ChevronDown size={15}/></div>
      <span className="nav-label">WORKSPACE</span>
      <nav>{([[LayoutDashboard,'Overview'],[Package,'Recoveries'],[Users,'Suppliers'],[Phone,'Call activity']] as const).map(([Icon, label]) => <button key={label} className={page === label ? 'nav-item active' : 'nav-item'} onClick={() => nav(label)}><Icon size={19}/>{label}{label === 'Recoveries' && <span className="nav-count">{recoveries.filter(r => r.status !== 'Approved').length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="agent-status"><span className="status-dot"/><strong>Your agent is ready</strong><p>Calls first. You stay in control.</p><div><Phone size={14}/><span/><MessageSquare size={14}/><span/><Mail size={14}/></div></div><button className="help" onClick={() => notify('Create a recovery, compare verified supplier quotes, then approve your preferred option. This workspace currently uses demo data.')}><CircleHelp size={18}/> Help & getting started <ArrowUpRight size={15}/></button><div className="account"><span className="avatar">JL</span><div><strong>Jamie Lee</strong><small>Business owner</small></div><MoreHorizontal size={19}/></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/> <span>{page}</span></div><div className="topbar-right"><span className="demo-badge">Demo workspace</span><span className="top-date">Sat, 12 Sep 2026</span></div></header>
    <main>
      <div className="page-heading"><div><div className="eyebrow">YOUR PROCUREMENT, UNDER CONTROL</div><h1>{page === 'Overview' ? 'Voice procurement' : page}</h1><p>{page === 'Overview' ? 'Say what you need. Your agent takes it from there.' : page === 'Suppliers' ? 'Your authorised supplier list. ABN verification is required before outreach.' : page === 'Call activity' ? 'Every conversation. Every detail. All in one place.' : 'From a missed delivery to a verified replacement.'}</p></div><button className="primary" onClick={() => setModal(true)}><Mic size={18}/> Talk to your agent</button></div>
      {(page === 'Overview' || page === 'Recoveries') && <>
        <section className="voice-entry"><div className="voice-orb"><Mic size={27}/></div><div><span className="eyebrow">ONE CONVERSATION. PROCUREMENT HANDLED.</span><h2>“I need 30 kilos of chicken by 8 am, under $350.”</h2><p>Your agent calls authorised suppliers, compares quotes, and gets it sorted.</p></div><button className="primary" onClick={() => setModal(true)}><Mic size={16}/> Start talking</button></section><div className="flow-strip"><span><Mic size={14}/> Tell us what you need</span><ChevronRight size={13}/><span><ShieldCheck size={14}/> ABN-verified suppliers</span><ChevronRight size={13}/><span><Phone size={14}/> Call & compare</span><ChevronRight size={13}/><span><CheckCheck size={14}/> Buy or confirm with you</span></div><section className="metrics"><Metric title="Active recoveries" value={String(recoveries.filter(r => r.status !== 'Approved').length).padStart(2,'0')} note={`${recoveries.filter(r => r.status === 'Needs approval').length} waiting for your decision`} icon={<Package size={18}/>}/><Metric title="Recovered this week" value={String(recoveries.filter(r => r.status === 'Approved').length).padStart(2,'0')} note="From your demo requests" icon={<CheckCheck size={18}/>}/><Metric title="Time spent on calls" value="3m 12s" note="Handled by your voice agent" icon={<Phone size={18}/>}/><Metric title="Below budget" value="$35" note="On the recommended recovery" icon={<ArrowDownLeft size={18}/>}/></section>
        <div className="section-header"><div className="section-title"><h2>Recovery workspace</h2><span className="count">{recoveries.length}</span></div><label className="search"><Search size={16}/><input aria-label="Search recoveries" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search recoveries…"/></label></div>
        <div className="recovery-layout"><section className="request-list">{filtered.map(r => <button key={r.id} className={`request-item ${r.id === selected ? 'selected' : ''}`} onClick={() => { setSelected(r.id); setTab('Overview') }}><div className="request-meta"><span>{r.id}</span><ChevronRight size={15}/></div><h3>{r.item}</h3><p>{r.quantity} {r.unit} <span>·</span> {money(r.budget)} budget</p><Badge status={r.status}/></button>)}{filtered.length === 0 && <p className="empty">No matching recoveries.</p>}<button className="add-request" onClick={() => setModal(true)}><Plus size={15}/> Create a recovery</button><div className="list-caption"><ShieldCheck size={16}/><span>Purchases follow your<br/>authorisation rules.</span></div></section>
        <section className="detail"><div className="detail-header"><div><div className="detail-kicker">{request.id} <span>/</span> {request.category}</div><h2>{request.item} <span>— {request.quantity}{request.unit === 'units' ? ' ' : ''}{request.unit}</span></h2></div><Badge status={request.status}/></div><div className="constraints"><span><Clock3 size={16}/>{new Date(request.deadline).toLocaleString('en-AU',{day:'numeric', month:'short',hour:'numeric',minute:'2-digit'})}</span><span><span className="dollar">$</span> {money(request.budget)} max budget</span><span><MapPin size={16}/>{request.location}</span></div>
        {request.purchaseMode && <div className="request-rules"><ShieldCheck size={15}/><span>{request.purchaseMode === 'preauthorised' ? `Pre-authorised up to ${money(request.budget)} when all requirements pass` : 'Confirm with you before buying'} · {request.confirmationChannel === 'sms' ? 'Confirmation by text' : 'Call you first, then text'}<em>Payment: {request.minimumPaymentDays ?? 0}+ days from invoice · deposit up to {request.maximumDepositPercent ?? 0}%</em>{request.brief && <em>“{request.brief}”</em>}</span></div>}<div className="tabs" role="tablist">{['Overview','Supplier quotes','Call transcripts'].map(t => <button role="tab" aria-selected={tab === t} className={tab === t ? 'tab active' : 'tab'} key={t} onClick={() => setTab(t)}>{t}{t === 'Supplier quotes' && <span>{seeded ? 3 : 0}</span>}</button>)}</div>
        {!seeded ? <div className="empty-state"><span className="empty-icon">{approved ? <CheckCheck/> : <Phone/>}</span><h3>{approved ? 'Recovery approved' : 'Ready for supplier outreach'}</h3><p>{approved ? 'This sample recovery has already been approved.' : 'Your request is captured. Connect the voice agent to find suppliers and collect real quotes.'}</p><span className="demo-badge">Demo · No live calls</span></div> : <>
        {tab === 'Overview' && <div className="detail-body"><section className={`recommendation ${approved ? 'approved' : ''}`}><div className="recommend-label"><span><Sparkles size={16}/>{approved ? 'SUPPLIER APPROVED' : 'RECOMMENDED RECOVERY'}</span><span className="verified"><ShieldCheck size={14}/> Verified by call</span></div><div className="recommend-main"><div className="supplier-heading"><span className="supplier-logo">VF</span><div><h3>Victorian Foods</h3><p>Exact match · {request.quantity}kg available</p></div></div><div className="price">$315<span>AUD · incl. delivery</span></div></div><div className="delivery-line"><Clock3 size={16}/><strong>Tomorrow, 7:00 am</strong><span>1 hour before your deadline</span></div><div className="checks">{Object.entries(validateOffer(offers[0],request)).map(([label,pass]) => <span key={label}>{pass ? <Check size={14}/> : <X size={14}/>} {label}</span>)}</div><div className="negotiated-terms"><strong>Payment terms improved</strong><span>Due on delivery → Net 14 from invoice · No deposit · No added fees</span><button className="text-button" onClick={() => setTab('Supplier quotes')}>Compare supplier rankings <ArrowRight size={14}/></button></div><div className="recommend-footer"><span><strong>$35 under budget.</strong> All requirements met.</span><button className="primary" disabled={approved} onClick={() => { setRecoveries(recoveries.map(r => r.id === selected ? {...r,status:'Approved'} : r)); notify('Supplier approved in this demo. No order or supplier message has been sent.') }}>{approved ? <><Check size={16}/> Approved</> : <>Approve supplier <ArrowRight size={16}/></>}</button></div></section>
        <div className="timeline-heading"><h3>Recovery activity</h3><span><Clock3 size={14}/> 3m 12s of calls</span></div><div className="timeline"><Timeline time="14:08" title="Recovery request created" description="30kg chicken breast · before 8:00 am · up to $350"/><Timeline time="14:08" title="3 alternative suppliers contacted" description="Your agent called to confirm stock, price and delivery." icon={<Phone size={14}/>}/><Timeline time="14:09" title="FreshFoods Wholesale" description="20kg available · $9.80/kg" badge="Insufficient quantity"/><Timeline time="14:10" title="Metro Poultry" description="30kg available · $300 total" badge="Misses deadline"/><Timeline time="14:11" title="Victorian Foods meets all requirements" description="30kg · $315 delivered · tomorrow at 7:00 am" success/>{approved && <Timeline time="Now" title="Approved by you" description="Supplier selection saved for this demo." success/>}</div><button className="text-button" onClick={() => setTab('Call transcripts')}>View call transcripts <ArrowRight size={15}/></button></div>}
        {tab === 'Supplier quotes' && <SupplierRanking offers={offers} request={request} onTranscript={setTranscript}/>}
        {tab === 'Call transcripts' && <div className="quotes-view">{offers.map(o => <CallRow key={o.id} offer={o} onClick={() => setTranscript(o)}/>)}</div>}
        </>}
        </section></div>
      </>}
      {page === 'Suppliers' && <section className="directory">{offers.map(o => <article className="supplier-card" key={o.id}><div className="supplier-heading"><span className="supplier-logo neutral">{o.initials}</span><div><h2>{o.name}</h2><p>Melbourne · Poultry & fresh produce · Demo supplier</p></div></div><div className="supplier-policy"><ShieldCheck size={16}/> ABN verification pending · Not eligible for live outreach</div><div className="supplier-stats"><div><span>Last quote</span><strong>{money(o.price)} <small>/ {o.quantity}kg</small></strong></div><div><span>Last contact</span><strong>12 Sep 2026</strong></div></div><details className="supplier-review"><summary>Check supplier history & terms</summary><p>On time: {o.onTimeDeliveries} of {o.completedOrders} demo orders. Payment: {paymentLabel(o.paymentDays)}. Deposit: {o.depositPercent}%. Added fees: {money(o.fees)}.</p><p>ABN verification must complete before any real outreach. History shown here is sample data.</p></details><button className="secondary" onClick={() => setTranscript(o)}><FileText size={16}/> View last conversation</button></article>)}</section>}
      {page === 'Call activity' && <section className="activity-page"><div className="section-header"><h2>Recent supplier calls</h2><span className="demo-badge">3 demo conversations</span></div>{offers.map(o => <CallRow key={o.id} offer={o} onClick={() => setTranscript(o)}/>)}<div className="channel-note"><Phone size={20}/><div><strong>A conversation comes first.</strong><p>SMS and email are follow-up channels when a supplier needs written details. No follow-ups sent.</p></div></div></section>}
      <footer><span><ShieldCheck size={14}/> Your rules. Your budget. Your agent handles the rest.</span><span>All amounts in AUD <span className="footer-dot">·</span> Sample data</span></footer>
    </main></div>
    {modal && <NewRecovery onClose={() => setModal(false)} onCreate={r => { setRecoveries([r,...recoveries]); setSelected(r.id); setPage('Recoveries'); setTab('Overview'); setModal(false); notify('Recovery created for this session. Live supplier calls are not connected yet.') }}/>}
    {transcript && <dialog className="transcript-panel" ref={node => { if (node && !node.open) node.showModal() }} onCancel={() => setTranscript(null)} aria-label="Call transcript"><button className="secondary" autoFocus onClick={() => setTranscript(null)}><ArrowLeft size={16}/> Back to workspace</button><div className="eyebrow">DEMO CALL TRANSCRIPT</div><h2>{transcript.name}</h2><p className="muted">12 Sep 2026 · {transcript.minutes} · Completed</p><div className="waveform">{Array.from({length:48},(_,i) => <i key={i} style={{height:`${12+((i*17)%35)}px`}}/>)}<span><Check size={14}/> Call complete</span></div><div className="speech"><span>BACKFILL AGENT</span><p>Hi, I’m calling on behalf of Flinders Kitchen. Can you supply 30kg of chicken breast, delivered to Flinders Lane before 8 am tomorrow?</p></div><div className="speech supplier"><span>{transcript.name.toUpperCase()}</span><p>We have {transcript.quantity} kilos available. The total is {money(transcript.price)}, including delivery. We can deliver {transcript.delivery.toLowerCase()}.</p></div><div className="speech"><span>BACKFILL AGENT</span><p>Could you offer at least 14 days from invoice, with no deposit? Please confirm any fees and the final total.</p></div><div className="speech supplier"><span>{transcript.name.toUpperCase()}</span><p>We can move from {paymentLabel(transcript.originalPaymentDays).toLowerCase()} to {paymentLabel(transcript.paymentDays).toLowerCase()}. The deposit is {transcript.depositPercent}%, with {money(transcript.fees)} in added fees. Total payable is {money(transcript.price + transcript.fees)}.</p></div><div className="speech"><span>BACKFILL AGENT</span><p>Thank you. I’ll pass those details to the owner for review. This is a quote enquiry, so no order is being placed.</p></div><div className="channel-note"><ShieldCheck size={20}/><p>Illustrative transcript for the UI prototype. A real call recording is not connected.</p></div></dialog>}
    {notice && <div className="toast" role="status"><Activity size={19}/><span>{notice}</span><button aria-label="Dismiss notification" onClick={() => setNotice('')}><X size={17}/></button></div>}
  </div>
}
function Metric({title,value,note,icon}:{title:string;value:string;note:string;icon:React.ReactNode}) { return <article className="metric"><div>{title}{icon}</div><strong>{value}</strong><span>{note}</span></article> }
function Badge({status}:{status:string}) { return <span className={`badge ${status === 'Approved' ? 'green' : status === 'Needs approval' ? 'amber' : 'neutral-badge'}`}><span className="status-dot"/>{status}</span> }
function Timeline({time,title,description,badge,icon,success}:{time:string;title:string;description:string;badge?:string;icon?:React.ReactNode;success?:boolean}) { return <div className="timeline-row"><time>{time}</time><span className={`timeline-node ${success ? 'success' : ''}`}>{success ? <Check size={14}/> : icon || <span/>}</span><div><strong>{title}</strong><p>{description} {badge && <span className="reason">{badge}</span>}</p></div></div> }
function CallRow({offer,onClick}:{offer:Offer;onClick:()=>void}) { return <button className="call-row" onClick={onClick}><span className="call-icon"><Phone size={18}/></span><div><strong>{offer.name}</strong><p>Chicken breast · Outbound call</p></div><span className="call-duration">{offer.minutes}</span><span className="call-completed"><Check size={14}/> Completed</span><ChevronRight size={18}/></button> }
