import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import { AuthGate } from './lib/supabase/AuthGate'
import './styles.css'
import './mobile.css'
import './recoveries.css'
import './intake.css'
import './registry.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AuthGate><App/></AuthGate></React.StrictMode>)
